# Generated by Django 5.2.13 on 2026-04-21 19:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_portfolio_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='withdrawal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
