# Generated by Django 5.2.13 on 2026-04-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_add_withdrawal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='kyc_note',
            field=models.TextField(blank=True, default='No KYC, no withdrawal.'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='withdrawal_note',
            field=models.TextField(blank=True, default='You are ineligible for withdrawal above $1000 at the moment'),
        ),
    ]
