# Generated by Django 5.2.13 on 2026-04-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_portfolio_kyc_note_portfolio_withdrawal_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='admin_withdraw_note',
            field=models.TextField(blank=True, default='You will be notified about this transaction soon.', verbose_name='Admin withdraw note'),
        ),
    ]
