# Generated by Django 5.2.13 on 2026-04-20 21:00

import apps.wallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, default=apps.wallet.models.generate_transaction_id, max_length=100, unique=True),
        ),
    ]
